export const comments = [
    "Teamwork makes it happen!",
    "Teamwork for the win!",
    "Mass following, unstoppable power!",
    "Teamwork, always the key!",
    "Mass following, endless potential!",
    "Teamwork conquers all!",
    "Mass following, big dreams!",
    "Teamwork is strength!",
    "Mass following, big impact!",
    "Together through teamwork!",
    "Teamwork wins the race!",
    "Mass following, massive impact!",
    "Teamwork is everything!",
    "Teamwork makes dreams real!",
    "Mass following, let's go!",
    "Power in teamwork!",
    "Teamwork creates success!",
    "Mass following, endless energy!",
    "Unity through teamwork!",
    "Teamwork brings results!",
    "Mass following makes it happen!",
    "Teamwork for success!",
    "Mass following, strong bond!",
    "Teamwork equals greatness!",
    "Teamwork = power!",
    "Mass following, massive force!",
    "Nothing beats teamwork!",
    "Mass following drives success!",
    "Teamwork for the future!",
    "Mass following, big achievements!",
    "Teamwork brings victory!",
    "Mass following creates magic!",
    "With teamwork, we rise!",
    "Mass following, unstoppable force!",
    "Teamwork moves mountains!",
    "Mass following, limitless success!",
    "Teamwork makes us strong!",
    "Mass following, pure power!",
    "Teamwork, the secret sauce!",
    "Mass following leads the way!",
    "Teamwork brings magic!",
    "Mass following, huge results!",
    "Teamwork brings us together!",
    "Mass following makes history!",
    "Teamwork powers dreams!",
    "Mass following, infinite reach!",
    "Together in teamwork!",
    "Teamwork changes everything!",
    "Mass following, the dream team!",
    "Teamwork achieves greatness!",
    "Mass following makes it real!",
    "Teamwork drives change!",
    "Mass following brings success!",
    "Teamwork never fails!",
    "Mass following is the key!",
    "Teamwork for excellence!",
    "Mass following, rising fast!",
    "Teamwork makes the impossible possible!",
    "Mass following, watch us grow!",
    "Teamwork creates opportunities!",
    "Mass following, we go further!",
    "Teamwork takes us higher!",
    "Mass following brings power!",
    "Teamwork equals victory!",
    "Mass following, reaching new heights!",
    "Teamwork makes magic happen!",
    "Mass following, powerful results!",
    "Teamwork builds success!",
    "Mass following, unstoppable growth!",
    "Teamwork creates leaders!",
    "Mass following, we're on top!",
    "Teamwork for innovation!",
    "Mass following brings energy!",
    "Teamwork fuels the fire!",
    "Mass following, let's go big!",
    "Teamwork is the foundation!",
    "Mass following, change makers!",
    "Teamwork pushes us forward!",
    "Mass following, making waves!",
    "Teamwork gets results!",
    "Mass following, we take over!",
    "Teamwork fuels progress!",
    "Mass following, uniting us all!",
    "Teamwork is our power!",
    "Mass following, the force!",
    "Teamwork turns vision into reality!",
    "Mass following, unstoppable momentum!",
    "Teamwork sparks greatness!",
    "Mass following, chasing success!",
    "Teamwork is the game changer!",
    "Mass following, creating waves!",
    "Teamwork, our greatest strength!",
    "Mass following, unstoppable momentum!",
    "Teamwork makes things happen!",
    "Mass following, we rise together!",
    "Teamwork is the heartbeat of success!",
    "Mass following, full speed ahead!",
    "Teamwork is where success starts!",
    "Mass following, let’s make it big!",
    "Teamwork creates leaders, not followers!",
    "Mass following, we lead the way!",
    "Teamwork, the winning formula!",
    "Mass following, endless potential!",
    "Teamwork brings us closer!",
    "Mass following, we’re on fire!",
    "Teamwork is the backbone of success!",
    "Mass following, we shine bright!",
    "Teamwork for limitless success!",
    "Mass following, we take control!",
    "Teamwork sets us apart!",
    "Mass following, breaking barriers!",
    "Teamwork makes things happen!",
    "Mass following, bigger and better!",
    "Teamwork is the key to success!",
    "Mass following, we're unstoppable!",
    "Teamwork makes the dream work!",
    "Mass following, limitless growth!",
    "Teamwork brings us together stronger!",
    "Mass following, we dominate!",
    "Teamwork creates winners!",
    "Mass following, rising high!",
    "Teamwork sparks success!",
    "Mass following, breaking new ground!",
    "Teamwork makes impossible things happen!",
    "Mass following, we reach further!",
    "Teamwork brings innovation!",
    "Mass following, the winning edge!",
    "Teamwork for the people!",
    "Mass following, we lead the pack!",
    "Teamwork leads to greatness!",
    "Mass following, reaching the stars!",
    "Teamwork makes it real!",
    "Mass following, taking over the world!",
    "Teamwork drives us forward!",
    "Mass following, the future is now!",
    "Teamwork brings out the best in us!",
    "Mass following, we're soaring!",
    "Teamwork builds success together!",
    "Mass following, moving mountains!",
    "Teamwork creates unstoppable power!",
    "Mass following, we make history!",
    "Teamwork unlocks potential!",
    "Mass following, unstoppable force of nature!",
    "Teamwork makes everything better!",
    "Mass following, we’re rising!",
    "Teamwork for everyone!",
    "Mass following, going global!",
    "Teamwork makes every challenge easy!",
    "Mass following, let's do this!",
    "Teamwork is where dreams are made!",
    "Mass following, driving change!",
    "Teamwork brings us closer to success!",
    "Mass following, we conquer!",
    "Teamwork makes progress happen!",
    "Mass following, reaching for the sky!",
    "Teamwork pushes limits!",
    "Mass following, we move forward!",
    "Teamwork brings out the best!",
    "Mass following, ready to win!",
    "Teamwork means achieving more!",
    "Mass following, we rise above!",
    "Teamwork fuels success!",
    "Mass following, unstoppable dream team!",
    "Teamwork makes the impossible possible!",
    "Mass following, the power of unity!",
    "Teamwork drives innovation!",
    "Mass following, chasing victory!",
    "Teamwork is the key to greatness!",
    "Mass following, the force of nature!",
    "Teamwork is success!",
    "Mass following, we’re on fire!",
    "Teamwork turns dreams into reality!",
    "Mass following, breaking all records!",
    "Teamwork creates something extraordinary!",
    "Mass following, always forward!",
    "Teamwork is the bridge to success!",
    "Mass following, turning the tide!",
    "Teamwork is the heartbeat of progress!",
    "Mass following, we take charge!",
    "Teamwork is the catalyst for success!",
    "Mass following, nothing can stop us!",
    "Teamwork builds a path to success!",
    "Mass following, unstoppable drive!",
    "Teamwork brings us closer to victory!",
    "Mass following, we lead the charge!",
    "Mass following, momentum is key!",
    "Teamwork inspires greatness!",
    "Mass following pushes boundaries!",
    "Teamwork keeps us moving forward!",
    "Mass following, reaching for the stars!",
    "Teamwork fuels ambition!",
    "Mass following, the dream is real!",
    "Teamwork is our victory road!",
    "Mass following, no stopping us now!",
    "Teamwork changes lives!",
    "Mass following, unstoppable journey!",
    "Teamwork ignites the fire within!",
    "Mass following, a force to be reckoned with!",
    "Teamwork makes the impossible happen!",
    "Mass following, breaking new limits!",
    "Teamwork elevates us all!",
    "Mass following, breaking new heights!",
    "Teamwork drives the impossible forward!",
    "Mass following, we aim high!",
    "Teamwork powers the revolution!",
    "Mass following, we never back down!",
    "Teamwork takes us to the top!",
    "Mass following, we make things happen!",
    "Teamwork builds dreams together!",
    "Mass following, the strength of unity!",
    "Teamwork transforms the world!",
    "Mass following, leading the charge!",
    "Teamwork rises above the rest!",
    "Mass following, unstoppable momentum!",
    "Teamwork makes the vision a reality!",
    "Mass following, destined for greatness!",
    "United we achieve greatness!",
    "Together, we’re unstoppable!",
    "Teamwork creates endless possibilities!",
    "Collective power drives success!",
    "With unity, we conquer!",
    "Strength in numbers, victory in teamwork!",
    "Teamwork makes the impossible achievable!",
    "When we unite, magic happens!",
    "Collaboration is the key to success!",
    "Together, we change the game!",
    "The power of teamwork, limitless and bold!",
    "Mass following, bigger goals ahead!",
    "Strength comes from standing together!",
    "Teamwork ignites the spark of victory!",
    "We rise by lifting each other up!",
    "Collaboration is the secret weapon!",
    "Greatness begins with teamwork!",
    "Together, we break barriers!",
    "In unity, we find power!",
    "One team, one dream!",
    "Success is built on collaboration!",
    "Teamwork makes us invincible!",
    "Our strength is in our unity!",
    "United we stand, unstoppable we fall!",
    "Teamwork unlocks limitless success!",
    "Collaboration leads us to new heights!",
    "Mass following, one shared vision!",
    "Teamwork equals unmatched success!",
    "Together, we make things happen!",
    "Success is sweeter when shared!",
    "The bigger the team, the bigger the impact!",
    "Mass following, unstoppable journey!",
    "Great things are built together!",
    "Teamwork is the path to victory!",
    "Alone we can do so little, together we can do so much!",
    "The power of teamwork is endless!",
    "A united front leads to unbeatable success!",
    "Collaboration fuels the fire of success!",
    "Mass following, unstoppable momentum!",
    "Together we rise, together we shine!",
    "Teamwork paves the way to success!",
    "Together, we make history!",
    "Teamwork is the engine that drives success!",
    "Mass following, stronger than ever!",
    "Great things happen when we collaborate!",
    "Strength in unity, power in numbers!",
    "The power of teamwork drives us forward!",
    "Success is a team effort!",
    "Teamwork unlocks infinite potential!",
    "Together, we make the impossible possible!",
    "Our power is in our collaboration!",
    "Teamwork creates waves of success!",
    "With teamwork, every challenge is conquerable!",
    "Together, we create limitless possibilities!",
    "Teamwork forges the path to greatness!",
    "Collaboration turns dreams into reality!",
    "Our unity is our strength!",
    "Mass following, we create a legacy!",
    "Success is the result of collective effort!",
    "Teamwork makes dreams come true!",
    "Alone we can achieve, but together we soar!",
    "Mass following, the engine of innovation!",
    "Teamwork drives our vision forward!",
    "We rise, we conquer, we achieve together!",
    "Strength lies in unity and teamwork!",
    "Teamwork accelerates progress!",
    "Mass following, we push the limits!",
    "Together, we build our future!",
    "Collaboration leads us to new victories!",
    "Teamwork turns ideas into reality!",
    "Our combined effort creates success!",
    "Teamwork is the cornerstone of greatness!",
    "Mass following, we never stop!",
    "Alone we may struggle, together we thrive!",
    "Mass following, unstoppable forces unite!",
    "We achieve greatness by working together!",
    "Teamwork transforms potential into success!",
    "Mass following, a force to be reckoned with!",
    "Together, we make the dream work!",
    "Teamwork creates an unstoppable ripple effect!",
    "Strength in teamwork, power in unity!",
    "Success is a shared victory!",
    "Teamwork turns vision into action!",
    "Mass following, together we move mountains!",
    "In collaboration, we find strength!",
    "Teamwork brings power to progress!",
    "United we push past limits!",
    "Together, we make the world a better place!",
    "Mass following, endless energy for change!",
    "Teamwork creates a future we can all build!",
    "Through teamwork, we create endless opportunities!",
    "Together we’re stronger, better, faster!",
    "Teamwork makes the impossible achievable!",
    "Mass following, nothing stands in our way!",
    "Collaboration brings the power of change!",
    "In unity, we find endless strength!",
    "Teamwork forges ahead toward success!",
    "Mass following, we’re rewriting the rules!",
    "Success starts with teamwork, always!",
    "Together, we make everything possible!",
    "Together, we’re a force of nature!",
    "Teamwork: Where dreams become reality!",
    "Mass following, setting new standards!",
    "Collaboration turns vision into action!",
    "With teamwork, there’s no limit to success!",
    "Our strength lies in our unity!",
    "Mass following, unstoppable in pursuit!",
    "Teamwork propels us to new heights!",
    "Mass following, driving transformation!",
    "Teamwork creates momentum like no other!",
    "Mass following, let's make an impact!",
    "The future belongs to the united!",
    "Teamwork fuels us to greatness!",
    "Mass following, bigger and better every day!",
    "We achieve more when we work together!",
    "Together, we’re rewriting history!",
    "Unity in action creates unstoppable power!",
    "Teamwork makes success sustainable!",
    "Mass following, changing the world together!",
    "Success is powered by collaboration!",
    "Teamwork builds bridges to greatness!",
    "Mass following, the key to extraordinary results!",
    "Teamwork turns obstacles into opportunities!",
    "With teamwork, nothing is out of reach!",
    "Mass following, together we elevate the game!",
    "Teamwork fuels our ambition and growth!",
    "Mass following, the engine of success!",
    "We’re unstoppable when we unite!",
    "Teamwork shapes the future of success!",
    "Mass following, we’re on the rise!",
    "Together, we create something amazing!",
    "Collaboration is the catalyst for progress!",
    "Teamwork makes success a reality!",
    "Mass following, unstoppable in spirit!",
    "Together, we make the impossible achievable!",
    "Mass following, a global movement of strength!",
    "Teamwork drives innovation and excellence!",
    "Success begins with us coming together!",
    "Mass following, united for greatness!",
    "Teamwork brings our dreams to life!",
    "Together, we turn challenges into victories!",
    "Mass following, paving the way for change!",
    "Teamwork creates lasting impact!",
    "Unity transforms challenges into triumphs!",
    "Mass following, we make magic happen!",
    "The power of teamwork is limitless!",
    "Mass following, success is just the beginning!",
    "Teamwork unlocks doors to new opportunities!",
    "With teamwork, we turn dreams into plans!",
    "Mass following, together we’re destined for success!",
    "Teamwork brings vision to life!",
    "Mass following, building a legacy of success!",
    "Teamwork empowers us to reach new heights!",
    "Together, we achieve the unimaginable!",
    "Mass following, we’re stronger than ever before!",
    "With teamwork, we turn ideas into realities!",
    "Teamwork creates a ripple effect of success!",
    "Mass following, we take charge of the future!",
    "Collaboration makes success a shared journey!",
    "Teamwork is the driving force of innovation!",
    "Mass following, we create the change we seek!",
    "Together, we’re an unstoppable force of progress!",
    "Teamwork transforms possibilities into achievements!",
    "Mass following, unstoppable energy for growth!",
    "Together, we rise, together we soar!",
    "Teamwork is the heart of any success!",
    "Mass following, united we succeed!",
    "Teamwork turns challenges into stepping stones!",
    "Mass following, the spark of transformation!",
    "Together, we’re creating a new era of success!",
    "Teamwork amplifies our power and potential!",
    "Mass following, the heartbeat of innovation!",
    "Teamwork makes greatness a team effort!",
    "Mass following, we lead with strength!",
    "Teamwork transforms challenges into triumphs!",
    "Mass following, no obstacle is too big!",
    "When we unite, we make the impossible happen!",
    "Teamwork creates pathways to success!",
    "Mass following, the dream team in action!",
    "Teamwork drives us to achieve the extraordinary!",
    "Mass following, success is within reach!",
    "Teamwork brings vision and action together!",
    "Mass following, we rise above the competition!",
    "Together, we achieve the unimaginable!",
    "Teamwork is the foundation of every victory!",
    "Mass following, we’re setting new records!",
    "With teamwork, we break all boundaries!",
    "Mass following, we’re on the fast track to success!",
    "Teamwork propels us to greatness!",
    "Mass following, changing the world one step at a time!",
    "Together, we create the future we want!",
    "Mass following, strength in numbers!",
    "Teamwork makes the impossible possible!",
    "Mass following, building a stronger tomorrow!",
    "With teamwork, we can accomplish anything!",
    "Teamwork ignites the spark of change!",
    "Mass following, we shape the future together!",
    "Teamwork makes the dream work, always!",
    "Mass following, let's achieve the unachievable!",
    "Teamwork takes us to places we’ve never been!",
    "Mass following, united for success!",
    "With teamwork, there’s no limit to what we can achieve!",
    "Mass following, breaking boundaries with unity!",
    "Teamwork is the fuel for greatness!",
    "Mass following, we go further together!",
    "Teamwork powers the path to success!",
    "Mass following, unstoppable in every way!",
    "Together, we create the path to victory!",
    "Teamwork turns goals into reality!",
    "Mass following, creating waves of change!",
    "Teamwork amplifies our strengths!",
    "Mass following, making dreams happen!",
    "Together, we write the story of success!",
    "Mass following, pushing the limits of greatness!",
    "Teamwork creates opportunities for all!",
    "Mass following, paving the road to success!",
    "Teamwork is the force that moves us forward!",
    "Mass following, we never stop growing!",
    "With teamwork, the sky’s the limit!",
    "Teamwork makes things happen faster!",
    "Mass following, we keep reaching higher!",
    "Together, we conquer new frontiers!",
    "Teamwork makes the impossible possible!",
    "Together, we’re unstoppable in pursuit of greatness!",
    "Mass following, united we lead!",
    "Teamwork is the foundation of all success!",
    "We rise by lifting each other up through teamwork!",
    "Mass following, the power of unity!",
    "With teamwork, nothing is too big to tackle!",
    "Together we are stronger, faster, and better!",
    "Mass following, achieving the extraordinary!",
    "Teamwork fuels progress and success!",
    "Mass following, we shape the future together!",
    "Through collaboration, we unlock infinite potential!",
    "Teamwork brings us closer to greatness!",
    "Mass following, where dreams come true!",
    "Together, we make things happen!",
    "Teamwork amplifies success and impact!",
    "Mass following, we're creating a legacy!",
    "Our unity makes us unstoppable!",
    "Mass following, breaking down barriers together!",
    "With teamwork, we are invincible!",
    "Mass following, driving change every step of the way!",
    "Teamwork turns obstacles into opportunities!",
    "Mass following, we’re changing the game!",
    "Together we win, together we thrive!",
    "Mass following, limitless growth ahead!",
    "Teamwork is our strength, unity is our power!",
    "Mass following, we’re on a mission to succeed!",
    "Teamwork creates the momentum we need to win!",
    "Mass following, reaching new heights every day!",
    "Together, we can overcome anything!",
    "Mass following, we’re setting the standard for success!",
    "With teamwork, we create boundless opportunities!",
    "Mass following, we inspire change around the world!",
    "Teamwork transforms challenges into achievements!",
    "Mass following, let’s reach the impossible!",
    "Together, we turn dreams into reality!",
    "Mass following, a collective force of greatness!",
    "Teamwork powers the future of success!",
    "Mass following, creating waves of change!",
    "Teamwork makes every challenge easier!",
    "Mass following, united in pursuit of success!",
    "Together we create momentum for progress!",
    "Mass following, we're a movement of power and progress!",
    "Teamwork brings everyone closer to victory!",
    "Mass following, we achieve greatness together!",
    "Together, we break all limits!",
    "Mass following, transforming the world one step at a time!",
    "Teamwork builds bridges to success!",
    "Mass following, let’s make the impossible happen!",
    "With teamwork, we rewrite the rules of success!",
    "Mass following, we lead the way with unity!",
    "Teamwork fuels the journey to victory!",
    "Mass following, we’re achieving the unachievable!",
    "Together, we create lasting impact!",
    "Mass following, unstoppable in pursuit of greatness!",
    "Teamwork turns vision into action!",
    "Mass following, we inspire each other to succeed!",
    "Together, we conquer the impossible!",
    "Mass following, the power of collective action!",
    "Teamwork creates a future full of possibilities!",
    "Mass following, taking on new challenges together!",
    "Together, we push the boundaries of success!",
    "Mass following, driving innovation and change!",
    "Teamwork is the driving force of greatness!",
    "Mass following, where unity meets success!",
    "Together, we rise above all challenges!",
    "Mass following, united in our mission for success!",
    "Teamwork unlocks the door to limitless potential!",
    "Mass following, let’s create a new era of success!",
    "Together, we make the impossible real!",
    "Mass following, unstoppable energy for progress!",
    "Teamwork brings out the best in all of us!",
    "Mass following, building a legacy of achievement!",
    "Together, we can achieve anything we set our minds to!",
    "Mass following, the power of togetherness!",
    "Teamwork drives us to new horizons!",
    "Mass following, pushing boundaries every day!",
    "Together, we rise to every challenge!",
    "Mass following, we never stop striving for more!",
    "Teamwork accelerates our journey to success!",
    "Mass following, we’re making history together!",
    "Together, we build the path to greatness!",
    "Mass following, the fuel that powers innovation!",
    "Teamwork creates a force that’s unstoppable!",
    "Mass following, we take charge of our future!",
    "Together, we are a force to be reckoned with!",
    "Mass following, shaping the future of success!",
    "Teamwork unlocks the door to limitless achievement!",
    "Mass following, no limits, just results!",
    "Together, we make the impossible achievable!",
    "Mass following, creating waves of innovation!",
    "Teamwork is the key to turning ideas into reality!",
    "Mass following, we push beyond limits!",
    "Together, we create a world of possibilities!",
    "Mass following, the foundation of unstoppable progress!",
    "Teamwork makes us stronger, better, and faster!",
    "Mass following, let’s turn vision into victory!",
    "Together, we rise to the challenge!",
    "Mass following, one united force for success!",
    "Teamwork builds the future we dream of!",
    "Mass following, the power to drive transformation!",
    "Together, we overcome every challenge!",
    "Mass following, uniting for a common goal!",
    "Teamwork fuels the power of innovation!",
    "Mass following, leading with unity and strength!",
    "Together, we create results that matter!",
    "Mass following, let’s break new ground!",
    "Teamwork is the spark that ignites greatness!",
    "Mass following, no challenge is too great!",
    "Together, we’re shaping the future of success!",
    "Mass following, unstoppable in our pursuit of excellence!",
    "Teamwork turns dreams into action!",
    "Mass following, let’s make things happen together!",
    "Together, we create unstoppable momentum!",
    "Mass following, we push the limits of greatness!",
    "Teamwork makes the dream work, every time!"
];


